name: Build Test

on:
  workflow_dispatch:

env:
  GIT_URL: "${{ github.server_url }}/${{ github.repository }}.git"
  BRANCH: "master"
  # github runners currently have two cores
  NR_JOBS: "2"

  CARL_PARSER_GIT_URL: "https://github.com/ths-rwth/carl-parser"
  CARL_PARSER_BRANCH: "master14"
  CARL_GIT_URL: "https://github.com/smtrat/carl"
  CARL_BRANCH: "master14"

  CMAKE_DEBUG: "-DCMAKE_BUILD_TYPE=Debug"
  CMAKE_RELEASE: "-DCMAKE_BUILD_TYPE=Release"
  CARL_CMAKE_DEBUG: "-DCMAKE_BUILD_TYPE=Debug -DUSE_CLN_NUMBERS=ON -DUSE_GINAC=ON -DTHREAD_SAFE=ON -DBUILD_ADDONS=ON -DBUILD_ADDON_PARSER=ON"
  CARL_CMAKE_RELEASE: "-DCMAKE_BUILD_TYPE=Release -DUSE_CLN_NUMBERS=ON -DUSE_GINAC=ON -DTHREAD_SAFE=ON -DBUILD_ADDONS=ON -DBUILD_ADDON_PARSER=ON"

  DOCUMENTATION_DISTRO: "ubuntu-20.04"

jobs:
  noDeploy:
    runs-on: ubuntu-latest
    env:
      PYTHON: "python3"
    strategy:
      matrix:
        # exclude debian-9 as it is broken
        distro: ["ubuntu-20.04", "ubuntu-18.04", "debian-10"]
        debugOrRelease: ["debug", "release"]

    steps:
      - name: Setup environment variables
        # this is strangely the best way to implement environment variables based on the value of another
        # GITHUB_ENV is a magic variable pointing to a file; if a line with format {NAME}={VALUE}
        # then the env variable with name NAME will be created/updated with VALUE
        run: |
          ([[ ${{ matrix.debugOrRelease }} == "debug" ]] && echo "CMAKE_ARGS=${CMAKE_DEBUG}" || echo "CMAKE_ARGS=${CMAKE_RELEASE}") >> $GITHUB_ENV
          ([[ ${{ matrix.debugOrRelease }} == "debug" ]] && echo "CARL_CMAKE_ARGS=${CARL_CMAKE_DEBUG}" || echo "CARL_CMAKE_ARGS=${CARL_CMAKE_RELEASE}") >> $GITHUB_ENV
          ([[ ${{ matrix.debugOrRelease }} == "debug" ]] && echo "DEBUG_SWITCH=--debug" || true) >> $GITHUB_ENV
      - name: Init Docker
        run: sudo docker run -d -it --name ci --privileged movesrwth/storm-basesystem:${{ matrix.distro }}
        # We should not do partial updates :/
        # but we need to install some dependencies
        # Surely we can find a better way to do this at some point
      - name: Update base system
        run: |
          sudo docker exec ci apt-get update
          sudo docker exec ci apt-get upgrade -qqy
      - name: install dependencies
        run: sudo docker exec ci apt-get install -qq -y maven uuid-dev libeigen3-dev python3 python3-venv
      - name: Git clone
        run: |
          sudo docker exec ci git clone --depth 1 --branch $BRANCH $GIT_URL /opt/pycarl
          sudo docker exec ci git clone --depth 1 --branch $CARL_BRANCH $CARL_GIT_URL /opt/carl
          sudo docker exec ci git clone --depth 1 --branch $CARL_PARSER_BRANCH $CARL_PARSER_GIT_URL /opt/carl-parser

      - name: Run cmake for carl
        run: sudo docker exec ci bash -c "mkdir /opt/carl/build; cd /opt/carl/build; cmake .. ${CARL_CMAKE_ARGS}"
      - name: Build carl
        run: sudo docker exec ci bash -c "cd /opt/carl/build; make lib_carl -j ${NR_JOBS}"

      - name: Run cmake for carl-parser
        run: sudo docker exec ci bash -c "mkdir /opt/carl-parser/build; cd /opt/carl-parser/build; cmake .. ${CMAKE_ARGS}"
      - name: make carl-parser
        run: sudo docker exec ci bash -c "cd /opt/carl-parser/build; make -j ${NR_JOBS}"

      - name: Setup virtualenv
        run: |
          sudo docker exec ci bash -c "cd /opt; ${PYTHON} -m venv pycarl-env; source pycarl-env/bin/activate; python --version"
      - name: Build pycarl
        run: |
          sudo docker exec ci bash -c "cd /opt; source pycarl-env/bin/activate; cd /opt/pycarl; python setup.py build_ext $DEBUG_SWITCH -j ${NR_JOBS} develop"
      - name: Run tests
        run: |
          sudo docker exec ci bash -c "cd /opt; source pycarl-env/bin/activate; cd /opt/pycarl; python setup.py test"

        # build and publish documentation
      - name: Install documentation dependencies
        if: matrix.debugOrRelease == 'release' && matrix.distro == env.DOCUMENTATION_DISTRO
        run: sudo docker exec ci bash -c "cd /opt; source pycarl-env/bin/activate; cd pycarl; pip install sphinx sphinx_bootstrap_theme"
      - name: Build documentation
        if: matrix.debugOrRelease == 'release' && matrix.distro == env.DOCUMENTATION_DISTRO
        run: |
          sudo docker exec ci bash -c "cd /opt; source pycarl-env/bin/activate; cd pycarl/doc; make html"
          sudo docker exec ci rm -r /opt/pycarl/doc/build/html/_sources
          sudo docker cp ci:/opt/pycarl/doc/build/html .
      - name: Deploy documentation
        if: matrix.debugOrRelease == 'release' && matrix.distro == env.DOCUMENTATION_DISTRO
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
